project:
  type: website

website:
  title: "Welcome to my blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/tejas2157/ADTA-5410.git
      - icon: file-person
        file: Tejaskumar Patel Resume.pdf
        
format:
  html:
    theme: cosmo
    css: styles.css
    

editor: visual

