{
  "hash": "be766e67dac19f01535fbe6f5d483396",
  "result": {
    "markdown": "---\ntitle: \"Linear regression\"\nauthor: \"Tejaskumar Patel\"\ndate: \"2023-12-14\"\ncategories: [R, Regression, analysis]\nimage: \"image.jpg\"\n---\n\n\nHi, Let's run a regression\n\n#### **Data Set Description**\n\n## **Boston housing data**\n\nThe dataset contains information about various factors affecting housing prices in Boston. The dataset includes 13 variables,which are,\n\n1.  **crim:** per capita crime rate by town.\n2.  **zn:** proportion of residental land zoned for lots over 25,000 sq.ft.\n3.  **indus:** proportion of non-retail business acres per town.\n4.  **chas:** charls river dummy variable( 1 if tract bounds river; 0 otherwise\n5.  **nox:** Nitrogen oxides concentration(parts per 10 million)\n6.  **rm:** Average number of rooms per dwelling.\n7.  **age:** Proportion of owner-occupied units built prior to 1940.\n8.  **dis:** Weighted distances to five Boston employment centers.\n9.  **rad:** Index of accessibility to radial highways.\n10. **tax:** Full-value property tax rate per \\$10,000.\n11. **ptratio:** Pupil-teacher ratio by town.\n12. **lstat:** Percentage of lower status of the population.\n\nThe target variable is,\n\n1.  **medv:** Median value of owner-occupied homes in \\$1000.00\n\n**Task 1:**\n\nIn this task I will load the Boston housing dataset and named it as\"mydata\". after that, I will calculate summary of the model to predict the \"medv\".\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ISLR2)\n\nmydata <- ISLR2::Boston\n\nmodel <- lm(medv ~., data=mydata)\n\nsummary(model)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = medv ~ ., data = mydata)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-15.1304  -2.7673  -0.5814   1.9414  26.2526 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  41.617270   4.936039   8.431 3.79e-16 ***\ncrim         -0.121389   0.033000  -3.678 0.000261 ***\nzn            0.046963   0.013879   3.384 0.000772 ***\nindus         0.013468   0.062145   0.217 0.828520    \nchas          2.839993   0.870007   3.264 0.001173 ** \nnox         -18.758022   3.851355  -4.870 1.50e-06 ***\nrm            3.658119   0.420246   8.705  < 2e-16 ***\nage           0.003611   0.013329   0.271 0.786595    \ndis          -1.490754   0.201623  -7.394 6.17e-13 ***\nrad           0.289405   0.066908   4.325 1.84e-05 ***\ntax          -0.012682   0.003801  -3.337 0.000912 ***\nptratio      -0.937533   0.132206  -7.091 4.63e-12 ***\nlstat        -0.552019   0.050659 -10.897  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 4.798 on 493 degrees of freedom\nMultiple R-squared:  0.7343,\tAdjusted R-squared:  0.7278 \nF-statistic: 113.5 on 12 and 493 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n**Conclusion of the model summary:**\n\nI can say that the estimated median value of owner-occupied houses is 41.62 when all predictors are zero because the intercept is statistically significant.\n\nHere, R squared is 0.7343 that means the model shows about 73.43% of the variability in the response variable.\n\nOverall, The model has low P-values and high R-squared value which indicates that the model is statistically significant.\n\n**Task 2:**\n\nHere, I will Generate a scatter plot of Housing Price(rm) vs. Median Value(medv)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\n# Create a scatter plot for medv and crim\nggplot(mydata, aes(x = rm, y = medv)) +\n  geom_point() +\n  labs(title = \"Scatter Plot of Housing Prices vs. Median Value in Boston\",\n       x = \"rm\",\n       y = \"medv\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n**Conclusion :**\n\nThere is positive correlation between average number of rooms (rm) and the median value of homes (medv).which indicate that as the average number of rooms increases, the median value of homes increase as well.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Histogram of housing prices\nhist(Boston$medv, main=\"Histogram of Median Home Values\", \n     xlab=\"Median Value of Homes\", col=\"lightblue\", border=\"black\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# Boxplot\nboxplot(medv ~ cut(rm, breaks=seq(3, 9, by=1)), data=Boston, \n        main=\"Boxplot of Median Home Values by Number of Rooms\",\n        xlab=\"Number of Rooms\", ylab=\"Median Value of Homes\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(corrplot)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\ncorrplot 0.92 loaded\n```\n:::\n\n```{.r .cell-code}\ncor_matrix <- cor(mydata)\n\ncorrplot(cor_matrix, method = \"color\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}